spring:
  application:
    name: service-registry
server:
  port: 8761
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
management:
  endpoints:
    web:
      exposure:
        # unsafe!
        include: '*'